# Generated by Django 5.1.6 on 2025-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('store', models.CharField(choices=[('A', 'Store A'), ('B', 'Store B')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
