# Generated by Django 5.1.6 on 2025-02-16 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)])),
                ('member_type', models.CharField(choices=[('admin', '관리자'), ('owner', '대표'), ('manager', '점주'), ('normal', '일반회원')], max_length=20)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('sex', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('age_group', models.PositiveSmallIntegerField()),
                ('phone_num', models.CharField(max_length=13)),
                ('member_password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('email', models.EmailField(max_length=254)),
                ('total_spent', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('last_visited', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('store', models.CharField(choices=[('A', 'Store A'), ('B', 'Store B')], max_length=50, null=True)),
                ('store_num', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('earning_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
