# Generated by Django 5.1.6 on 2025-02-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, '10대'), (20, '20대'), (30, '30대'), (40, '40대'), (50, '50대'), (60, '60대 이상')], null=True),
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
