# Generated by Django 5.1.6 on 2025-02-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0006_alter_member_age_group_delete_notice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("phone_num", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("10대", "10대"),
                            ("20대", "20대"),
                            ("30대", "30대"),
                            ("40대", "40대"),
                            ("50대", "50대"),
                            ("60대 이상", "60대 이상"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("남성", "남성"), ("여성", "여성")], max_length=10
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
