# Generated by Django 5.1.6 on 2025-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0007_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="store_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="store_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="store_time",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="store",
            field=models.CharField(
                choices=[("A", "서초점"), ("B", "강남점")], max_length=50, null=True
            ),
        ),
    ]
