# Generated by Django 5.1.6 on 2025-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_eventpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnareply',
            name='author_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
