# Generated by Django 5.1.6 on 2025-03-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_qnareply_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('admin', '관리자'), ('manager', '점주'), ('normal', '일반회원')], default='normal', max_length=20),
        ),
    ]
