# Generated by Django 5.1.6 on 2025-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_member_member_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='store',
            field=models.CharField(choices=[('A', '서초점'), ('B', '강남점')], max_length=50, null=True),
        ),
    ]
