# Generated by Django 5.1.6 on 2025-03-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_eventpost_is_pinned_eventpost_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='event_detail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
