# Generated by Django 5.1.6 on 2025-03-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_eventpost_is_pinned_eventpost_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='store',
            field=models.CharField(choices=[('A', '서초점'), ('B', '강남점')], max_length=50, null=True),
        ),
    ]
