# Generated by Django 5.1.6 on 2025-03-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_qna_store'),
        ('member', '0013_eventpost_event_detail'),
    ]

    operations = [
    ]
