# Generated by Django 5.1.6 on 2025-03-11 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_merge_20250311_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
