# Generated by Django 5.1.6 on 2025-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('top_banner', '상단 배너'), ('brand', '브랜드 이미지')], max_length=15)),
                ('position', models.CharField(blank=True, choices=[('top_banner_1', '상단배너1'), ('top_banner_2', '상단배너2'), ('top_banner_3', '상단배너3')], max_length=15, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
