# Generated by Django 5.1.6 on 2025-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='store',
            field=models.CharField(choices=[('A', '서초점'), ('B', '강남점')], max_length=50, null=True),
        ),
    ]
