# Generated by Django 5.1.6 on 2025-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
