# Generated by Django 5.1.6 on 2025-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
