# Generated by Django 5.1.6 on 2025-02-16 08:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('store', models.CharField(choices=[('A', 'Store A'), ('B', 'Store B')], max_length=50)),
                ('sale_price', models.IntegerField(null=True)),
                ('cost_price', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('desert', '디저트류'), ('bread', '빵류'), ('cake', '케이크류')], max_length=50)),
                ('best', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='allergy', serialize=False, to='menu.item')),
                ('allergy_wheat', models.BooleanField(default=False)),
                ('allergy_milk', models.BooleanField(default=False)),
                ('allergy_egg', models.BooleanField(default=False)),
                ('allergy_soybean', models.BooleanField(default=False)),
                ('allergy_nuts', models.BooleanField(default=False)),
                ('allergy_etc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition_info', serialize=False, to='menu.item')),
                ('nutrition_weight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)])),
                ('nutrition_calories', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('nutrition_sodium', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('nutrition_sugar', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nutrition_carbohydrates', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nutrition_saturated_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nutrition_trans_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nutrition_protein', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
            ],
        ),
    ]
