# Generated by Django 5.1.6 on 2025-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_name_eng',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
