# Generated by Django 5.1.6 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_item_item_name_eng"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
