# Generated by Django 5.1.6 on 2025-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("dessert", "디저트류"), ("bread", "빵류")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="store",
            field=models.CharField(
                choices=[("A", "서초점"), ("B", "강남점")], max_length=50
            ),
        ),
    ]
