# Generated by Django 5.1.6 on 2025-02-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0004_alter_item_category_alter_item_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
