# Generated by Django 5.1.6 on 2025-03-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_item_category_alter_item_store'),
        ('menu', '0005_alter_item_item_image'),
    ]

    operations = [
    ]
