# Generated by Django 5.1.6 on 2025-03-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_merge_20250304_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
