name: Dev-Deploy

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  build-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: DEBUG - Check if secrets are loaded
        run: |
          echo "USERNAME: $DOCKER_USERNAME"
          echo "TOKEN: $DOCKER_TOKEN"
        env:
          DOCKER_USERNAME: ${{ secrets.DEV_DOCKERHUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DEV_DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DEV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DEV_DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DEV_DOCKERHUB_USERNAME }}/breadscanso-dev:latest
          build-args: |
            DJANGO_SETTINGS_MODULE=breadscanso.settings_dev

      - name: Copy deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: 3.34.46.30
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "deploy.sh"
          target: "~/breadscanso-dev"

      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 3.34.46.30
          username: ubuntu
          key: ${{ secrets.DEV_SSH_KEY }}
          envs: DOCKER_DEV_IMAGE
          script: |
            export DOCKER_DEV_IMAGE=${{ secrets.DEV_DOCKERHUB_USERNAME }}/breadscanso-dev:latest
            chmod +x ~/breadscanso-dev/deploy.sh
            ~/breadscanso-dev/deploy.sh
