name: Dev-Deploy

on:
  push:
    branches:
      - dev

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DEV_DOCKERHUB_USERNAME }}
          password: ${{ secrets.DEV_DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_DEV_IMAGE }}
          build-args: |
            DJANGO_SETTINGS_MODULE=breadscanso.settings_dev

      - name: Copy deploy.sh to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.209.132.161
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          source: "deploy.sh"
          target: "~/breadscanso-dev"

      - name: Run deploy.sh on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.209.132.161
          username: ec2-user
          key: ${{ secrets.DEV_SSH_KEY }}
          envs: DOCKER_DEV_IMAGE
          script: |
            export DOCKER_DEV_IMAGE=${{ secrets.DOCKER_DEV_IMAGE }}
            chmod +x ~/breadscanso-dev/deploy.sh
            ~/breadscanso-dev/deploy.sh
