# Generated by Django 5.1.6 on 2025-02-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('earned_points', models.IntegerField()),
                ('store', models.CharField(choices=[('A', 'Store A'), ('B', 'Store B')], max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('item_total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.orderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('credit', 'Credit Card'), ('cash', 'Cash')], max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('card_name', models.CharField(blank=True, max_length=10, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.orderinfo')),
            ],
        ),
    ]
