# Generated by Django 5.1.6 on 2025-02-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_eventpost_qna_qnareply'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField(default=0)),
                ('store', models.CharField(choices=[('A', 'Store A'), ('B', 'Store B')], max_length=50)),
                ('earned_points', models.IntegerField(default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_count', models.IntegerField()),
                ('item_price', models.IntegerField(default=0)),
                ('item_total', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.orderinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('credit', '카드'), ('cash', '현금')], max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('card_name', models.CharField(blank=True, max_length=10, null=True)),
                ('approval_code', models.CharField(blank=True, max_length=5, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.orderinfo')),
            ],
        ),
    ]
