# Generated by Django 5.1.6 on 2025-02-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
    ]
