# Generated by Django 5.1.6 on 2025-02-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20250218_1348'),
    ]

    operations = [
    ]
