# Generated by Django 5.1.6 on 2025-02-18 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_auto_20250218_1352'),
        ('member', '0003_eventpost_qna_qnareply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='member',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member'),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='pay_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='card_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
    ]
