# Generated by Django 5.1.6 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0004_remove_orderinfo_member_paymentinfo_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinfo",
            name="final_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderinfo",
            name="used_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="used_points",
            field=models.IntegerField(default=0),
        ),
    ]
