# Generated by Django 5.1.6 on 2025-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_orderinfo_final_amount_orderinfo_used_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
