# Generated by Django 5.1.6 on 2025-02-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0006_orderinfo_total_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinfo",
            name="payment_method",
            field=models.CharField(
                choices=[("credit", "카드"), ("epay", "간편결제")], max_length=20
            ),
        ),
    ]
