# Generated by Django 5.1.6 on 2025-02-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_orderinfo_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(null=True),
        ),
    ]
