# Generated by Django 5.1.6 on 2025-02-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0007_alter_paymentinfo_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinfo",
            name="used_points",
        ),
    ]
