# Generated by Django 5.1.6 on 2025-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kiosk", "0008_remove_paymentinfo_used_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinfo",
            name="used_points",
            field=models.IntegerField(default=0),
        ),
    ]
