# Generated by Django 5.1.6 on 2025-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_remove_orderinfo_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
