# Generated by Django 5.1.6 on 2025-03-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_orderinfo_total_count'),
        ('kiosk', '0009_paymentinfo_used_points'),
    ]

    operations = [
    ]
