"""
Django settings for breadscanso project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR = ", BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&=9$0a5lsdo@uvu5qy%50!jbc6iqtx%f+862^2i#u^ec!!b362'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#
# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ["www.breadscanso.shop", "breadscanso.shop", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django_summernote',  # 텍스트 에디터 summernote 추가
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # template의 intcomma 활성화,
    'kiosk',
    'brand',
    'event',
    'member',
    'menu',
    'notice',
    'pay',
    'qna',
    'sales',
    'stock',
    'store',
    'store_info',
    'ebhealthcheck.apps.EBHealthCheckConfig', # eb 상태 관리(CI/CD 안정화)
    'django.contrib.sites', #추가한것
    # allauth 앱 추가
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
    # 'corsheaders',  # ♦️지우지마세요♦️
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    "allauth.account.middleware.AccountMiddleware", # allauth middleware 추가
]

# CORS_ALLOW_ALL_ORIGINS = True
#
#
# CORS_ALLOWED_ORIGINS = [
#     "https://www.breadscanso.shop",
#     "https://breadscanso.shop"
# ]



ROOT_URLCONF = ('breadscanso.urls')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'breadscanso.wsgi.application'





# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# 언어
LANGUAGE_CODE = 'ko-kr'

# 지역대
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 클라어언트 요청중 정적파일 구분 키워드 선언
STATIC_URL = 'static/'

# staticfiles 디렉토리 지정
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# 로그인 후 이동할 기본 페이지 설정
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/' # 구글로그인 연동 추가

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # 기본 인증 백엔드
    # 'allauth' 이메일 로그인과 같은 특정 인증 방법
    'allauth.account.auth_backends.AuthenticationBackend',
]

# AUTH_USER_MODEL = 'member.Member'

LOGIN_URL = '/main/login/'  # 실제 로그인 URL에 맞게 수정


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'naver': {
            'SCOPE': [
                'profile',
                'email',
            ],
            'AUTH_PARAMS': {
                'response_type': 'code',
            }
        }
    }


SOCIALACCOUNT_LOGIN_ON_GET = True  # 이 설정이 핵심
# SOCIALACCOUNT_AUTO_SIGNUP = True   # 추가 정보 입력 없이 자동 가입

SITE_ID = 1 # django.contrib.sites 프레임워크 다중 사이트 지원 관련, SITE_ID값 1은 기본 사이트를 지정한다. (django_site 테이블의 첫 번째 레코드)
ACCOUNT_EMAIL_REQUIRED = True # 회원가입시 email 필수입력
ACCOUNT_EMAIL_VERIFICATION = 'none' # none | optional | mandatory
# LOGIN_REDIRECT_URL = '/app/' # 기본값 /accounts/profile/
# LOGOUT_REDIRECT_URL = '/app/'  # 기본값 /
ACCOUNT_LOGOUT_ON_GET = True # 기본값 False
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'  # allauth가 리디렉션 URL을 https로 생성
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # HTTPS 프록시 신뢰
# SECURE_SSL_REDIRECT = True  # 모든 HTTP 요청을 HTTPS로 자동 리디렉션

ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'

# 환경 구분을 위한 설정 (조건문 사용)
if DEBUG:
    print("개발 환경 설정 적용")
    SECURE_SSL_REDIRECT = False
else:
    print("운영 환경 설정 적용")
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#---------------------------------------#
# summernote 로컬 저장소 지정
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Summernote 설정
SUMMERNOTE_CONFIG = {
    'summernote': {
        'width': '100%',
        'height': '400',
        'lang': 'ko-KR',
        'toolbar': [
            ['style', ['style']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['style', ['bold', 'italic', 'underline', 'strikethrough', 'clear']],
            ['color', ['color']],
            ['table', ['table']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['insert', ['picture', 'link', 'video']],
            ['view', ['fullscreen', 'help']],
        ],
        'fontNames': ['Arial', 'Comic Sans MS', 'Courier New', '맑은 고딕', '궁서', '굴림체', '돋음체', '바탕체'],
        'fontSizes': ['8', '9', '10', '11', '12', '14', '16', '18', '20', '22', '24', '28', '30', '36', '50', '72', '96'],
    },
    'attachment_upload_to': 'summernote/',  # 미디어 폴더 내 하위 경로
    # 'attachment_upload_to': '',  # 로컬 업로드 비활성화
    # 'attachment_require_authentication': True,
    # 'attachment_handler': 'notice.utils.upload_notice_image_to_s3',  # S3 업로드 핸들러
    'disable_attachment': False,  # 첨부 파일 기능 활성화
    'jquery': 'window.jQuery',
    'iframe': True,
}

#---------------------------------------#



# """
# Django settings for breadscanso project.
#
# Generated by 'django-admin startproject' using Django 5.1.6.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# print("BASE_DIR = ", BASE_DIR)
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-&=9$0a5lsdo@uvu5qy%50!jbc6iqtx%f+862^2i#u^ec!!b362'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True
# #
# # ALLOWED_HOSTS = []
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.humanize',  # template의 intcomma 활성화,
#     'kiosk',
#     'brand',
#     'event',
#     'member',
#     'menu',
#     'notice',
#     'pay',
#     'qna',
#     'sales',
#     'stock',
#     'store',
#     'store_info',
#     'ebhealthcheck.apps.EBHealthCheckConfig' # eb 상태 관리(CI/CD 안정화)
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
#
# ROOT_URLCONF = ('breadscanso.urls')
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates']
#         ,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'breadscanso.wsgi.application'
#
#
# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/
#
# # 언어
# LANGUAGE_CODE = 'ko-kr'
#
# # 지역대
# TIME_ZONE = 'Asia/Seoul'
#
# USE_I18N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/
#
# # 클라어언트 요청중 정적파일 구분 키워드 선언
# STATIC_URL = 'static/'
#
# # staticfiles 디렉토리 지정
# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]
#
# # 로그인 후 이동할 기본 페이지 설정
# LOGIN_REDIRECT_URL = "/"
# LOGOUT_REDIRECT_URL = "/"
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
